# Generated by Django 3.2.4 on 2021-06-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Serie', models.CharField(max_length=200)),
                ('Atomic_mass', models.FloatField()),
                ('Enetgy_level', models.IntegerField()),
                ('Electronegativity', models.FloatField()),
                ('Electron_affinity', models.FloatField()),
                ('melting_point', models.FloatField()),
                ('vaporization_point', models.FloatField()),
                ('Potencial_de_ionização', models.FloatField()),
                ('Dureza', models.FloatField()),
                ('Módulo', models.FloatField()),
                ('Densidade', models.FloatField()),
                ('Condutividade_termica', models.FloatField()),
                ('Condutividade_eletrica', models.FloatField()),
                ('Calor', models.FloatField()),
                ('Descobrimento', models.IntegerField()),
            ],
        ),
    ]
