# Generated by Django 3.2.4 on 2021-06-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_atom_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atom',
            old_name='Enetgy_level',
            new_name='Energy_level',
        ),
    ]
