# Generated by Django 3.2.4 on 2021-07-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_atom_atomic_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atom',
            name='Serie',
            field=models.CharField(choices=[('', ''), ('Alkali metals', 'Alkali metals'), ('Alkaline earth metals', 'Alkaline earth metals'), ('Lanthanoids', 'Lanthanoids'), ('Actinoids', 'Actinoids'), ('Transition metals', 'Transition metals'), ('Post-transition metals', 'Post-transition metals'), ('Metalloids', 'Metalloids'), ('Reactive nonmetals', 'Reactive nonmetals'), ('Noble gases', 'Noble gases'), ('Unknown', 'Unknown')], max_length=200),
        ),
    ]
