# Generated by Django 3.2.4 on 2021-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_atom_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('simbol', models.CharField(max_length=2)),
                ('mass', models.FloatField()),
                ('charge', models.FloatField()),
                ('spin', models.FloatField()),
                ('classification', models.CharField(choices=[('', ''), ('Quark', 'Quark'), ('Anti-quark', 'Anti-quark'), ('Lépton', 'Lépton'), ('Anti-lépton', 'Anti-lépton'), ('Bóson', 'Bóson')], max_length=200)),
            ],
        ),
    ]
