# Generated by Django 3.2.4 on 2021-07-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_particle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particle',
            name='simbol',
            field=models.CharField(max_length=3),
        ),
    ]
